language: node_js
node_js:
  - '4'
install:
  make i
script:
  make JEST_FLAGS=--coverage test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
